### ISSUE TITLE
Rename @status to @state

### ISSUE THREAD

**Issue by prymitive** [cloudflare/unsee#104]
It's time to release unsee 0.5, but there is one thing might need changing first, `@status` filter was added to the master branch to support new `status` key from Alertmanager >=0.6.1
`status` ended up being nested in Alertmanager (it was added to solve [AM issue 609](https://github.com/prometheus/alertmanager/issues/609) and that was a long PR with lots of changes),  current unsee implementation ended being slightly off with how Alertmanager is naming this, it should actually be `@state` rather than `@status`.

```
"status": {
    "inhibitedBy": [],
    "silencedBy": [],
    "state": "active"
}
```

[example](https://github.com/cloudflare/unsee/blob/master/mock/0.6.2/api/v1/alerts/groups#L21)

We should rename it before releasing 0.5, any objections @jamesog / @mattbostock / @Tenzer ?

**Comment by jamesog** [comment]
Seems like a good idea to me.

**Comment by Tenzer** [comment]
No objections from me. Unsee (and Alertmanager) is a fast moving project so breaking changes are to be expected at this point.
