### ISSUE TITLE
Make this repo public

### ISSUE THREAD

**Issue by prymitive** [cloudflare/unsee#11]
There are a few open PRs, can we open this repo once they are merged?
Are there any other outstanding issues preventing us from making it public?

Small tasks to be done once it's open:
- [x] Add mock data to this repo - pointless before it's marked public as we won't be able to access those files
- [x] Setup travis - we could use CI, travis will be easy to add
- [ ] Build an official docker image and put it on docker hub ?

**Comment by mattbostock** [comment]
🎉

**Comment by prymitive** [comment]
Made a PR for travis - #17

**Comment by prymitive** [comment]
will deploy a new build internally and if all goes well we'll tag a release

**Comment by prymitive** [comment]
Repo is public so closing
