### ISSUE TITLE
Links in annotations?

### ISSUE THREAD

**Issue by filippog** [cloudflare/unsee#152]
Hi!
thanks for unsee! I'd like to include clickable links in annotation text (e.g. link to relevant logs, dashboards, etc) is there a way to do that? AFAICS the annotation text now isn't styled in any way.

thanks!

**Comment by prymitive** [comment]
All annotation with URLs in the value should be converted into links and rendered as button, you can see this on the example screenshot: ![screenshot](https://raw.githubusercontent.com/cloudflare/unsee/master/screenshot.png)
Notice dashboard links there.
If some links are not converted into such then it's a bug, can you share an example that doesn't work?

**Comment by filippog** [comment]
@prymitive nice, thanks! Using an url-only annotation works as expected, I thought e.g. https links would be rendered as clickable items _inside_ annotation text e.g. "Foobar has an alert, see logs at https://...". I'm closing this as I think it is resolved!

**Comment by prymitive** [comment]
Current behavior is mostly driven by how we setup alert annotations at Cloudflare. If you put links as part of a larger text I can add support for that easily. Let's re-open it.

**Comment by prymitive** [comment]
Raised #156 to add this

**Comment by filippog** [comment]
Sounds good, thanks @prymitive! FTR I was satisfied with the annotation-based solution because the links in question are very long (kibana dashboards)
