### ISSUE TITLE
Option for inverse of STRIP_LABELS

### ISSUE THREAD

**Issue by byblakout** [cloudflare/unsee#170]
We're trying to clear up / simplify our `unsee` dashboard by using `STRIP_LABELS` - which is great. However many exporters add additional labels and adding them all to a list can be tedious.

Could a `INCLUDE_LABELS` option be added, where we specifically say: we want to see labels `a`, `b,` and `c`, but nothing else?

Thank ya.

**Comment by peimanja** [comment]
+1

**Comment by prymitive** [comment]
Seems like a good idea

**Comment by prymitive** [comment]
Will be fixed via #171 which will also fix a bug I found when adding this.

**Comment by peimanja** [comment]
Awesome!
