### ISSUE TITLE
Support for both private and public endpoints for alertmanager

### ISSUE THREAD

**Issue by sylr** [cloudflare/unsee#182]
Hi,

Here my setup 

 - Unsee in a docker container accessible from internet through oauth2_proxy.
 - Alertmanager in a docker container accessible from both a private network with no authentication and from internet trough oauth2_proxy.
 - Unsee talks to Alertmanager  via the private network.

It works well but the silence feature unfortunately tries to use this private address of the Alertmanager declared in the conf.

It would be nice if we could define for each Alertmanagers a public ip that the silence feature would use.

Cheers.

**Comment by prymitive** [comment]
I think I'll need to add a config file first for this, having complex syntax for flags / env variables isn't great.

**Comment by prymitive** [comment]
#190 was closed by adding proxy support for client->unsee->alertmanager requests, does that help with this issue?

**Comment by sylr** [comment]
It should! I will test it!  Thanks.

**Comment by prymitive** [comment]
Can we close this now with proxy support in 0.9?

**Comment by sylr** [comment]
Yes! Thanks.
