### ISSUE TITLE
Build ERROR: use of internal package not allowed 

### ISSUE THREAD

**Issue by sareddy7** [cloudflare/unsee#183]
Trying to build with go 1.9 and i am getting this error tried 0.8 and master.
```bash
  [11] ./unsee.js 12.7 kB {0} [built] [prefetched]
  [15] ./templates.js 2.84 kB {0} [built]
  [25] ./alerts.js 5.69 kB {0} [built]
  [27] ./autocomplete.js 2.04 kB {0} [built]
  [28] ./colors.js 1.68 kB {0} [built]
  [29] ./config.js 3.45 kB {0} [built]
  [37] ./filters.js 7.63 kB {0} [built]
  [50] ./counter.js 1.81 kB {0} [built]
  [51] ./grid.js 1.43 kB {0} [built]
  [53] ./summary.js 1.82 kB {0} [built]
 [266] ./progress.js 1.03 kB {0} [built]
 [270] ./silence.js 13.5 kB {0} [built]
 [271] ./unsilence.js 3.07 kB {0} [built]
 [272] ./watchdog.js 1.71 kB {0} [built]
 [273] ./help.js 126 bytes {1} [built] [prefetched]
    + 273 hidden modules
go-bindata-assetfs  -prefix assets -nometadata assets/templates/... assets/static/dist/...
go build -ldflags "-X main.version="
alerts.go:6:2: use of internal package not allowed
main.go:10:2: use of internal package not allowed
alerts.go:7:2: use of internal package not allowed
alerts.go:8:2: use of internal package not allowed
views.go:13:2: use of internal package not allowed
main.go:11:2: use of internal package not allowed
make: *** [unsee] Error 1
```
Please help me. Thanks 
@prymitive any thoughts

**Comment by mattbostock** [comment]
@sareddy7: You'll need to build unsee inside a GOPATH, e.g.:

```
mkdir -p ~/go/src/github.com/cloudflare
cd ~/go/src/github.com/cloudflare
git clone git@github.com:cloudflare/unsee.git
cd unsee
```

**Comment by sareddy7** [comment]
@mattbostock 
`/sainath/goprojects/src/go/src/github.com/cloudflare/unsee` 
is my project dir now prev it was under `/sainath/goprojects/src/`
still getting this error
GOPATH in bash_profile is `/sainath/goprojects`

**Comment by mattbostock** [comment]
@sareddy7 You should either set your `GOPATH` to `/sainath/goprojects/src/go` or consider moving directories so that the repo is in `/sainath/goprojects/src/github.com/cloudflare/unsee`.

**Comment by sareddy7** [comment]
@mattbostock awesome, thanks . I missed the directory structure mentioned in [building Doc](https://github.com/cloudflare/unsee#building-and-running) while trying to fix a bunch of GO issues. First time building go projects. 
Thanks again for your quick responses.

**Comment by mattbostock** [comment]
@sareddy7: Glad you got it sorted.
