### ISSUE TITLE
Support Alertmanager with TLS Auth?

### ISSUE THREAD

**Issue by zenman94** [cloudflare/unsee#184]
Dear all,

I have many Alertmanager and somes with TLS auth. 
Is it possible to use a client cert in Unsee to scrape alerts?

Regards

**Comment by prymitive** [comment]
Same as with #182, this would make configuration too complex to expres it with env variables. I need to switch to a config file before it can be implemented.

**Comment by prymitive** [comment]
Raised a PR for that, will likely need some work before merging
