### ISSUE TITLE
Proxy client requests through unsee instance

### ISSUE THREAD

**Issue by tonobo** [cloudflare/unsee#190]
We've protected the alertmanager and unsee instances directly over the proxyserver. 
But submitting silences will not work, because the the alertmanager is directly queried from client side.
Possibly is there any ability to proxy those requests through unsee instance to alertmanager.

**Comment by prymitive** [comment]
Similar to #182, need to start work on 0.9 release that should include a config file, since any additional complexity will be a bit tricky to express purely via ENV variables.

**Comment by sylr** [comment]
@prymitive As far as I'm concerned I would prefer that you implement this than what I proposed  in #182.

Cheers.

**Comment by prymitive** [comment]
#202 adds support for this feature, you can test it by building unsee from `proxy` branch and adding `proxy: true` to the Alertmanager instance config, example:

```yaml
alertmanager:
  interval: 60s
  servers:
    - name: local
      uri: http://localhost:9093
      timeout: 10s
      proxy: true
```

**Comment by davidkarlsen** [comment]
Is it possible to enable proxy through use of environment variables?

**Comment by prymitive** [comment]
No, any setup that needs a fine tuned configuration requires a config file as it gets tricky to keep config parsing simple.
But by "fine tuned" I mostly mean multiple Alertmanager instances, for most people it's probably just one and that should be possible to configure fully with just envs. I could add and env that sets the proxy flag globally on.

**Comment by davidkarlsen** [comment]
@prymitive It would be great if you could add that - love configuring it all through env vars (and yes, I only have one alert manager)

**Comment by prymitive** [comment]
#214 should address that

**Comment by davidkarlsen** [comment]
Awesome - thanks a lot!

**Comment by davidkarlsen** [comment]
Do you have an ETA for the next release?

**Comment by prymitive** [comment]
As soon as @terinjokes  helps me with #207 and it's merged. I'll try to bribe him with some coffee today, so I think we can aim for next week.
We have auto build setup on https://hub.docker.com/r/cloudflare/unsee/tags/ so there's always master docker image if you want to try it today.

**Comment by davidkarlsen** [comment]
Hm. I run 0.9.1 and have set the env var ALERTMANAGER_PROXY=true
``` 
docker inspect monitoring_unsee_1 |grep ALERTMANAGER_PROXY
                "ALERTMANAGER_PROXY=true",
[root@alp-aot-ccm02 ~]# 
```

Nevertheless I get:
Connection to the remote endpoint failed

when attempting to set a silence? (alerts are displaying fine, so it's not a connection err)

**Comment by tonobo** [comment]
I use the new config format, this works great. I also pulled just a few hours ago, so the master is also working with proxy option.

**Comment by prymitive** [comment]
You should see log line like this when unsee starts
```
INFO[0000] [foo] Configured Alertmanager source at https://example.com (proxied: false) 
INFO[0000] [bar] Configured Alertmanager source at https://example.com (proxied: true) 
```
can you check if proxy is set there?

**Comment by davidkarlsen** [comment]
@prymitive no there: 
```
Jan 29 17:56:40 alp-aot-ccm02 docker/2b4db6bcbb0a[17967]: time="2018-01-29T16:56:40Z" level=info msg="[default] Configured Alertmanager source at http://alertmanager:9093 (proxied: false)"
[et2448@alp-aot-ccm02 ~]$ 
```

**Comment by prymitive** [comment]
I can't reproduce that with v0.9.1:

```
$ LOG_CONFIG=false ALERTMANAGER_PROXY=true ALERTMANAGER_URI=https://example.com ./unsee 
INFO[0000] Reading configuration file unsee.yaml        
INFO[0000] Using simple config with a single Alertmanager server 
INFO[0000] Version: v0.9.1                              
INFO[0000] [default] Configured Alertmanager source at https://example.com (proxied: true) 
```

Care to open a ticket for that with some steps to reproduce?

**Comment by davidkarlsen** [comment]
Run the image like this (docker-compose format):
```
 unsee:
    image: cloudflare/unsee:v0.9.1
    restart: always
    environment: 
      - ALERTMANAGER_URIS=default:http://alertmanager:9093
      - WEB_PREFIX=/unsee/
      - SERVICE_CHECK_HTTP=/
      - ALERTMANAGER_PROXY=true
    depends_on:
     - alertmanager
```

**Comment by prymitive** [comment]
That's the issue: `ALERTMANAGER_URIS=default:http://alertmanager:9093`
`ALERTMANAGER_URIS` still works for compatibility, but it's handled by legacy settings code and that one doesn't know about proxy.
Update your env to:
```
environment: 
      - ALERTMANAGER_URI=http://alertmanager:9093
      - WEB_PREFIX=/unsee/
      - SERVICE_CHECK_HTTP=/
      - ALERTMANAGER_PROXY=true
```
might want to add `ALERTMANAGER_NAME=default` but shouldn't be needed (can't remember what's the default name)

**Comment by davidkarlsen** [comment]
Thanks a lot!
