### ISSUE TITLE
Provide link to alertmanager silence

### ISSUE THREAD

**Issue by Kellel** [cloudflare/unsee#203]
When looking at a silenced alert it would be nice to be able to get a link to the silence in alertmanager.

If nothing else it would be acceptable to be able to get the silence id to search in amtool

**Comment by prymitive** [comment]
Care to elaborate in a bit more detail @Kellel?

**Comment by Kellel** [comment]
![screenshot from 2017-12-08 09-39-07](https://user-images.githubusercontent.com/1751124/33777981-abd7cc6c-dbfb-11e7-8224-44b69bb86f3f.png)

So In this screenshot I would like to be able to get the silence_id of the silence or just a link to the silence in alertmanager

**Comment by prymitive** [comment]
Let's start with showing the id, since Alertmanager API doesn't give us explicit URLs for silences in the UI.
