### ISSUE TITLE
Rewrite UI using react

### ISSUE THREAD

**Issue by prymitive** [cloudflare/unsee#208]
It's officially 2018, time for a cleaner UI code.
It should also use SSE or websockets instead of AJAX polling, which will require backend code changes.

**Comment by terinjokes** [comment]
SSE is uni-directional, but unsupported by Microsoft Edge. Using WebSockets, you could replace all the AJAX calls with RPCs sent over the WS connection, and also get push support.

Fortunately, you should be able to abstract the UI and event handlers alway from the transport enough to change your mind later: so doing polling with XHR is still a great start.

**Comment by prymitive** [comment]
The goal of SSE/ws is mostly to get rid of polling loop and get updates after the backend fetch new data from upstream (Alertmanager). It will also remove the need for caching, since all clients can subscribe to the same push channel (there needs to be more than one since each client can specify a different filter).

**Comment by prymitive** [comment]
Done in https://github.com/prymitive/karma, closing here
