### ISSUE TITLE
[::1]:53: read: connection refused

### ISSUE THREAD

**Issue by sylr** [cloudflare/unsee#235]
Hi,

Sometimes I get this error in the unsee UI

    Get http://prometheus-alertmanager-xxxxx/api/v1/silences: dial tcp: lookup prometheus-alertmanager-xxxxx on [::1]:53: read udp [::1]:55668->[::1]:53: read: connection refused 

I have to delete the UNSEE pods to make it disappear.

**Comment by prymitive** [comment]
The error indicates that the pod cannot resolve dns lookups when making HTTP requests to the Alertmanager. I don't think this has anything to do with unsee and it's purely local environment problem, am I missing something?

**Comment by sylr** [comment]
Yeah but it seems that if resolutions fails once for a target it does not come back ever even though resolution comes back again.

**Comment by sylr** [comment]
@prymitive I believe the error and the logs I get come from 

https://github.com/cloudflare/unsee/blob/master/internal/alertmanager/models.go#L71

Would it be possible that is detectVersion() crashes once it "evicts" the alertmanager ad vitam eternam ?

**Comment by sylr** [comment]
I think I found the issue.

I mounted the unsee config volume at `/etc`, I shouldn't have done that, now that I've mounted it at `/etc/unsee` I don't have the problem anymore.
