### ISSUE TITLE
Silence on proxied alertmanagers give a 404

### ISSUE THREAD

**Issue by roidelapluie** [cloudflare/unsee#237]
Wger I try to create a silence, I get a 404 from unseen.

It is not even making API calls to alertmanager.

**Comment by prymitive** [comment]
It's really hard to fix an issue if no details are given. Can you provide steps to reproduce it? Capture requests in the browser and give config example? Without that there's nothing I can do to help.

**Comment by roidelapluie** [comment]
POST https://xxxx/unsee/proxy/alertmanager/xxxx/api/v1/silences gives a 404

**Comment by roidelapluie** [comment]
I also notice that the help link is wrong:  https://xxxx/unseehelp.

Mybe I miss trailing slash in "prefix"

**Comment by roidelapluie** [comment]
That was it. Missing trailing slash in "prefix"
