### ISSUE TITLE
Failed with AM 0.5.1

### ISSUE THREAD

**Issue by tcolgate** [cloudflare/unsee#24]
The silences format unsee is expecting seems different from what is being sent by alertmanager 0.5.1,
I see the following error.

```ERRO[0000] json: cannot unmarshal array into Go struct field SilenceAPIResponse.data of type alertmanager.silencesData ```

The changes in #23 resolved this error. It may be that you are running against a newer version of AM.

**Comment by prymitive** [comment]
#23 got merged but I need to merge #32 before I can cut `v0.2.0` that support Alertmanager `0.5`

**Comment by prymitive** [comment]
This went into `v0.2.0`, for `0.3` release I'll work on supporting both, it shouldn't be hard (#34).
