### ISSUE TITLE
Silences POST fails with 307 Temporary Redirect due to double-slash in URL

### ISSUE THREAD

**Issue by dswarbrick** [cloudflare/unsee#264]
When trying to create a silence in Unsee, the POST fails because it has a double-slash in the URL, causing Alertmanager to respond with a 307 Temporary Redirect.

For example, the initial POST goes to `http://ewr-alertmgr:9093//api/v1/silences` and fails with the 307. If I edit and resend the POST using Firefox developer console, with the extra slash removed, it succeeds.

Tested with Unsee 0.9.2 and Alertmanager 0.15.0-rc1.

**Comment by roidelapluie** [comment]
That is not a bug in unsee

**Comment by dswarbrick** [comment]
@roidelapluie You are right, I had launched Unsee with a trailing slash in the `--alertmanager.uri` option. My fault, sorry for the noise.

... although maybe it might be nice to have a warning / hint about this in the docs, or better yet, strip the trailing slash if some unsuspecting idiot like myself does that in future ;-)
