### ISSUE TITLE
Support alertmanager 0.15.x

### ISSUE THREAD

**Issue by giganteous** [cloudflare/unsee#267]
I'm using unsee against AM 0.15.1, and a few things look weird.
Can I verify myself if the new alertmanager is the culprit, or assist in debugging it?

The exact problem I'm experiencing: the alertname doesn't show in the header of an "incident block", it's promoted (or demoted) to the listing inside the incident block.

**Comment by djvl** [comment]
I experienced the same and rolled back to 0.14.0..

**Comment by prymitive** [comment]
@giganteous  / @djvl are you running Alertmanager via official docker images by any chance? If so there was a change in the path for the config file used in that docker image, if you updated image but didn't change but are still mounting the config under old path you might get default grouping, which might be related to what you're seeing.
I don't think that 0.15 introduced any API changes.

@terinjokes / @bobrik 
It doesn't look like anyone is maintaining this repo after I left cloudflare and it's a shame to see people raising issues and not getting any feedback.
Can I suggest to add a note to the top of the readme file warning people that it's no longer maintained? Or maybe even disable github issues?

**Comment by giganteous** [comment]
@prymitive Thanks for your reply, and the update on the maintenance of this project.

I've tried reproducting with the new 1.15.2, and the problem is now gone (still a problem on 1.15.1). @djvl can you confirm this?

**Comment by djvl** [comment]
I'm using an RPM install of alertmanager. After some digging it appears the default for 'group_by' has changed recently (v0.15.x), see: https://github.com/prometheus/alertmanager/issues/1288
So, when setting the following in 'alertmanager.yml' the old behavior is restored.
```
route:
  group_by: ['alertname']
```
@prymitive I switched to your repo and it looks good! Thanks for mentioning it.

**Comment by giganteous** [comment]
Cheers!
