### ISSUE TITLE
Handling different Alertmanager API variants

### ISSUE THREAD

**Issue by prymitive** [cloudflare/unsee#27]
Alertmanager API isn't stable yet, which means that `0.4` branch API is incompatible with `0.5`.
Let's cut `0.1` unsee branch that targets Alertmanager `0.4` and `0.2` branch that targets `0.5` API.
With that we can release `v0.1.0` of the `0.1` branch and start work on `v0.2.0`.
After that let's update `README` and document which unsee one needs for given Alertmanager version.

**Comment by prymitive** [comment]
What version scheme should we use for release branches?

1. Just the version like `0.1`?
2. 'v0.1` (but that's already for tags, so might be confusing)?
3. Maybe `release-0.1`?

I think nr 3 makes most sense to me.

**Comment by jamesog** [comment]
I vote no. 3.

**Comment by prymitive** [comment]
This (and branch naming) needs to be documented in [CONTRIBUTING](https://github.com/cloudflare/unsee/blob/master/CONTRIBUTING.md) docs.
We should probably automate releases too.

**Comment by prymitive** [comment]
Made a PR, it's easier to address comments that way.
