### ISSUE TITLE
Hide top bar and optionally replace with customizable headline

### ISSUE THREAD

**Issue by fabianseitzbn** [cloudflare/unsee#272]
It would be great if one could hide the top bar. If you use Unsee on some signage system, its interactive features cannot be used. Furthermore, the text is so small that it may be difficult to see the filter criteria. 

Connected to this: if you have several dashboards using Unsee, a description of the filtered alerts would be good, especially if several Unsee pages are alternating on the same screen. Therefore it would be helpful to optionally add a customizable headline by URL parameter.

**Comment by prymitive** [comment]
bad news: unsee doesn't have any active maintainer anymore
good news: https://github.com/prymitive/karma hides the top bar after a few minutes of inactivity

**Comment by fabianseitzbn** [comment]
Thanks, I have had a look at karma
